apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudguard.fullname" . }}
  labels:
    {{- include "cloudguard.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cloudguard.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloudguard.selectorLabels" . | nindent 8 }}
    spec:
      # --- NEW SECTION 1 ---
      # This tells the pod to use the ServiceAccount
      # that we are about to create.
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      # --- END NEW SECTION 1 ---

      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          # This tells kubernetes if a command is defined in values.yaml, use it.
          {{- if .Values.command }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- end }}

          # This loops through any extra arguments and turns them into flags (e.g. --host=0.0.0.0)
          {{- if .Values.extraArgs }}
          args:
            {{- range $key, $value := .Values.extraArgs }}
            - "--{{ $key }}={{ $value }}"
            {{- end }}
          {{- end }}


          # This injects the S3 bucket name from our values.yaml
          # into the container as an environment variable.
          # Our Python code (os.getenv) will read this.
          env:
            - name: "LOG_BUCKET_NAME"
              value: "{{ .Values.s3.log_bucket_name }}"
            - name: "MLFLOW_TRACKING_URI"
              value: "{{ .Values.mlflow.mlflow_tracking_uri }}"

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 60
