apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudguard.fullname" . }}
  labels:
    {{- include "cloudguard.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cloudguard.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloudguard.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: "100m"  # Request 10% of a CPU
              memory: "64Mi" # Request 64MB of Memory
            limits:
              cpu: "500m"  # Don't let it use more than 50% of a CPU
              memory: "128Mi"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
